### ISSUE TITLE
Dosya Adlarının Hepsi İngilizce Olsun

### ISSUE THREAD

**Issue by ercanersoy** [enginkuzu/Yeni-Bir-Programlama-Dili#1]
Merhabalar,

Bu projede dosya adlarının hepsi İngilizce olunca geniş bir kesim tarafından anlaşılacağını düşünüyorum. Bu sayede geliştirmiş oldujğunuz programlama dili ve bu dilin araçları daha çok kişi tarafından kullanılır, geliştirilir ve katkı yapılır.

**Comment by enginkuzu** [comment]
Merhaba Ercan,

Haklısın. Bazı tercihlerden dolayı (ki bunlar kişiden kişiye değişen şeyler) şimdilik böyle devam edecek. Neden böyle yaptığımı da içerecek şekilde -nasıl projeme katkı yapılacağını- (Contributing) anlatan bir döküman eklemeyi düşünüyorum.

Geri bildirimler benim için çok değerli. Düşüncelerini paylaştığın için çok teşekkür ediyorum.
